interface IDept {
    value: string;
    label: string;
  }
  
const sortDepts: Array<IDept> = [
    { value: "Computer Science", label: "Computer Science" },
    { value: "Biology", label: "Biology" },
    { value: "Chemistry", label: "Chemistry" },
    { value: "Biochemistry", label: "Biochemistry" },
    { value: "Biotechnology", label: "Biotechnology" },
    { value: "Mass Communication", label: "Mass Communication" },
    { value: "Geology", label: "Geology" },
    { value: "Geography", label: "Geography" },
    { value: "Physics", label: "Physics" },
    { value: "Statistics", label: "Statistics" },
    { value: "Agriculture Engineering", label: "Agriculture Engineering" },
    { value: "Computer Enginnering", label: "Computer Enginnering" },
    { value: "Chemical Engineering", label: "Chemical Engineering" },
    { value: "Civil Engineering", label: "Civil Engineering" },
    { value: "Microbiology", label: "Microbiology" },
    { value: "Industrial Chemistry", label: "Industrial Chemistry" },
    { value: "Zoology", label: "Zoology" },
    { value: "Botany", label: "Botany" },
    { value: "Agricultural Economics", label: "Agricultural Economics" },
    { value: "Animal Science", label: "Animal Science" },
    { value: "Crop Science", label: "Crop Science" },
    { value: "Horticulture", label: "Horticulture" },
    { value: "Archaeology", label: "Archaeology" },
    { value: "Architecture", label: "Architecture" },
    { value: "Building", label: "Building" },
    { value: "Enviromental Management", label: "Enviromental Management" },
    { value: "Quantity Surveying", label: "Quantity Surveying" },
    { value: "Forestry", label: "Forestry" },
    { value: "Fisheries", label: "Fisheries" },
    { value: "Technical Education", label: "Technical Education" },
    { value: "Business Education", label: "Business Education" },
    { value: "Library Studies", label: "Library Studies" },
    { value: "Food Science", label: "Food Science" },
    { value: "Environmental Engineering", label: "Environmental Engineering" },
    { value: "Engineering Management", label: "Engineering Management" },
    { value: "Farm Machinery Engineering", label: "Farm Machinery Engineering" },
    { value: "Transport Engineering", label: "Transport Engineering" },
    { value: "Maritime Technology", label: "Maritime Technology" },
    { value: "Mechanical Engineering", label: "Mechanical Engineering" },
    { value: "Production Engineering", label: "Production Engineering" },
    { value: "Metallurgical Engineering", label: "Metallurgical Engineering" },
    { value: "Textile Engineering", label: "Textile Engineering" },
    { value: "Fibre Science & Technology", label: "Fibre Science & Technology" },
    { value: "Mining Engineering", label: "Mining Engineering" },
    { value: "Petrochemical Engineering", label: "Petrochemical Engineering" },
    { value: "Public Health Engineering", label: "Public Health Engineering" },
    { value: "Ceramic Engineering", label: "Ceramic Engineering" },
    { value: "Communication Engineering", label: "Communication Engineering" },
    { value: "Industrial Engineering", label: "Industrial Engineering" },
    { value: "Electrical Engineering", label: "Electrical Engineering" },
    { value: "Electronic Engineering", label: "Electronic Engineering" },
    { value: "Urban & Regional Planning", label: "Urban & Regional Planning" },
    { value: "Fine Arts", label: "Fine Arts" },
    { value: "Industrial Design", label: "Industrial Design" },
    { value: "Meteorology", label: "Meteorology" },
    { value: "Estate Management", label: "Estate Management" },
    { value: "Nursing", label: "Nursing" },
    { value: "Medical Radiography", label: "Medical Radiography" },
    { value: "PhysioTherapy", label: "PhysioTherapy" },
    { value: "Medical Laboratory Science", label: "Medical Laboratory Science" },
    { value: "Pharmacy", label: "Pharmacy" },
    { value: "Geophysics", label: "Geophysics" },
    { value: "Industrial Mathematics", label: "Industrial Mathematics" },
    { value: "Industrial Physics", label: "Industrial Physics" },
    { value: "Applied Microbiology", label: "Applied Microbiology" },
    { value: "Applied Biochemistry", label: "Applied Biochemistry" },
    { value: "Veterinary Medicine", label: "Veterinary Medicine" },
    { value: "Wildlife Management", label: "Wildlife Management" },
    { value: "Wood & Paper Technology", label: "Wood & Paper Technology" },
    { value: "Art & Industrial Design", label: "Art & Industrial Design" },
    { value: "Fashion Design", label: "Fashion Design" },
    { value: "Printing Technology", label: "Printing Technology" },
    { value: "Foundry Engineering Technology", label: "Foundry Engineering Technology" },
    { value: "Textile Technology", label: "Textile Technology" },
    { value: "Chemical Engineering Technology", label: "Chemical Engineering Technology" },
    { value: "Civil Engineering Technology", label: "Civil Engineering Technology" },
    { value: "Ceramic & Glass Technology", label: "Ceramic & Glass Technology" },
    { value: "Petroleum Engineering Technology", label: "Petroleum Engineering Technology" },
    { value: "Leather Technology", label: "Leather Technology" },
    { value: "Irrigation Engineering Technology", label: "Irrigation Engineering Technology" },
    { value: "Mechanical Engineering Technology", label: "Mechanical Engineering Technology" },
    { value: "Metallurgical Engineering Technology", label: "Metallurgical Engineering Technology" },
    { value: "Mining Engineering Technology", label: "Mining Engineering Technology" },
    { value: "Mineral Resources Engineering", label: "Mineral Resources Engineering" },
    { value: "Marine Engineering Technology", label: "Marine Engineering Technology" },
    { value: "Computer Engineering Technology", label: "Computer Engineering Technology" },
    { value: "Architectural Technology", label: "Architectural Technology" },
    { value: "Building Technology", label: "Building Technology" },
    { value: "Cartography", label: "Cartography" },
    { value: "Photogrammetry", label: "Photogrammetry" },
    { value: "Land Surveying", label: "Land Surveying" },
    { value: "Town & Regional Planning", label: "Town & Regional Planning" },
    { value: "Hotel & Catering Management", label: "Hotel & Catering Management" },
    { value: "Nutrition & Dietetics", label: "Nutrition & Dietetics" },
    { value: "Tourism", label: "Tourism" },
    { value: "Home Economics & Management", label: "Home Economics & Management" },
    { value: "Library Science", label: "Library Science" },
    { value: "Science Laboratory Technology", label: "Science Laboratory Technology" },
    { value: "Food Technology", label: "Food Technology" },
    { value: "Rubber & Polymer Technology", label: "Rubber & Polymer Technology" },
    { value: "Agricultural Education", label: "Agricultural Education" },
    { value: "Home Economics Education", label: "Home Economics Education" },
    { value: "Technology Education", label: "Technology Education" },
    { value: "Computer Education", label: "Computer Education" },
    { value: "Creative Arts & Design", label: "Creative Arts & Design" },
  ]

  export const depts = sortDepts.sort( (a, b) => {
    if (a.value < b.value) {
      return -1;
    }
    if (a.value > b.value) {
      return 1;
    }
    return 0;
  });
  