import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Navbar } from "../components/NavBar";
import styles from "../styles/Home.module.scss";
import Link from "next/link";
import { FaGithub } from "react-icons/fa";
import { TiSocialLinkedinCircular } from "react-icons/ti";
import { AiFillTwitterCircle } from "react-icons/ai";

const Home = () => {
  const nums = [1, 2, 3, 4];
  return (
    <>
      <Head>
        <title>E-LogBook | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main>
        <section className={styles.hero}>
          <div className={styles.heroContent}>
            <h1>What's E-LogBook?</h1>
            <p>
              eLogbook is an electronic logbook designed to minimize keyboard
              use by students. This is an application that replaces the use of
              physical LogBook and also monitors student activities during
              SIWES.
            </p>
            <div>
              <Link href="/login">Login</Link>
              <Link href="/signup">Signup</Link>
            </div>
          </div>
        </section>
        <section className="my-2">
          <h1 className="font-bold text-2xl landscape:text-2xl md:text-5xl text-center text-[#eb0f5b]">
            Blog
          </h1>
          <p className="text-center font-bold md:text-3xl landscape:text-xl md:mt-4 landscape:mt-1">
            Top Headlines
          </p>

          <div className={styles.table}>
            <div className={styles.row}>
              <div
                className={`${styles.cell} ${styles.colspan2} h-full w-full`}
              >
                <img src="./images/image1.png" alt="blogpost" />
                <div>
                  <div>
                    <h1 className="font-bold text-red-300 text-2xl lit:text-lg landscape:text-xl md:text-5xl landscape:md:text-5xl">
                      BlogTitle 1
                    </h1>
                    <p className="text-xl font-light landscape:text-sm md:text-5xl lit:text-sm landscape:md:text-3xl leading-none">
                      Lorem ipsum dolor sit amet consectetur adipisicing elit.
                      Illum amet, inventore optio laudantium praesentium...
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div className={styles.row}>
              <div className="flex space-x-3 lit:flex-wrap lit:space-x-0 lit:space-y-3">
                <div className={styles.cell}>
                  <img src="./images/image1.png" alt="blogpost" />
                  <div>
                    <div>
                      <h1 className="font-bold text-red-300 text-xl landscape:text-xl md:text-4xl">
                        BlogTitle 2
                      </h1>
                      <p className="text-sm landscape:text-sm md:text-3xl leading-none">
                        Lorem ipsum dolor sit amet consectetur adipisicing
                        elit...
                      </p>
                    </div>
                  </div>
                </div>
                <div className={styles.cell}>
                  <img src="./images/image1.png" alt="blogpost" />
                  <div>
                    <div>
                      <h1 className="font-bold text-red-300 text-xl landscape:text-xl md:text-4xl">
                        BlogTitle 3
                      </h1>
                      <p className="text-sm landscape:text-sm md:text-3xl leading-none">
                        Lorem ipsum dolor sit amet consectetur adipisicing
                        elit...
                      </p>
                    </div>
                  </div>
                </div>
              </div>

              <div className={`${styles.cell} ${styles.rowspan2}`}>
                <img src="./images/image1.png" alt="blogpost" />
                <div>
                  <div>
                    <h1 className="font-bold text-red-300 text-2xl landscape:text-2xl md:text-4xl">
                      BlogTitle 4
                    </h1>
                    <p className="text-xl landscape:text-xl md:text-3xl leading-none">
                      Lorem ipsum dolor sit amet consectetur adipisicing elit...
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>

      <footer className={styles.footer}>
        <div className={styles.socialMedia}>
          <a href="https://twitter.com/am_vicolas" target="_blank">
            <AiFillTwitterCircle size="2rem" />
          </a>
          <a href="https://github.com/Vicolas11" target="_blank">
            <FaGithub size="1.7rem" />
          </a>
          <a href="https://linkedin.com/in/vicolas-akoh/" target="_blank">
            <TiSocialLinkedinCircular size="2.2rem" />
          </a>
        </div>
        <p>© Vicolas 2022. All rights reserved.</p>
      </footer>
    </>
  );
};

export default Home;
