import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Navbar } from "../components/NavBar";
import styles from "../styles/Home.module.scss";
import Link from "next/link";

const Home = () => {
  const nums = [1, 2, 3, 4];
  return (
    <div className={styles.container}>
      <Head>
        <title>E-LogBook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navbar />
      </header>

      <main className={styles.main}>
        <section className={styles.hero}>
          <div className={styles.heroContent}>
            <h1>What's E-LogBook?</h1>
            <p>
              eLogbook is an electronic logbook designed to minimize keyboard
              use by students. This is an application that replaces the use of
              physical LogBook and also monitors student activities during
              SIWES.
            </p>
            <Link href="/">Signup</Link>
          </div>
        </section>
        <section className={styles.blog}>
          <h1>Blog</h1>
          <p>Top Headlines</p>
          <div className={styles.blogImg}>
            {nums.map((num) => (
              <div className={`item${num}`}>
                <img src="./images/image1.png" alt="blogpost" />
                <div className={styles.overlay}>
                  <div>
                    <h1>BlogTitle</h1>
                    <p>
                      Lorem ipsum dolor sit amet consectetur adipisicing elit.
                      Illum amet, inventore optio laudantium praesentium
                    </p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </section>
      </main>

      <footer className={styles.footer}>
        <p>© Vicolas 2022. All rights reserved.</p>
      </footer>
    </div>
  );
};

export default Home;
